#!/bin/bash
set -e

BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}✓${NC} $1"; }
warn()  { echo -e "${YELLOW}!${NC} $1"; }
prompt(){ echo -ne "${BOLD}$1${NC} "; }

echo ""
echo -e "${BOLD}═══════════════════════════════════════${NC}"
echo -e "${BOLD}   Server Monitor Bot — Setup Wizard   ${NC}"
echo -e "${BOLD}═══════════════════════════════════════${NC}"
echo ""

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# 1. Telegram config
echo -e "${BOLD}1. Telegram Configuration${NC}"
prompt "Bot token (from @BotFather):" ; read -r BOT_TOKEN
prompt "Your Telegram chat ID:";        read -r CHAT_ID
echo ""

# 2. Server name
echo -e "${BOLD}2. Server Details${NC}"
prompt "Server name (e.g. my-vps) [$(hostname -s)]:"; read -r SERVER_NAME
[ -z "$SERVER_NAME" ] && SERVER_NAME=$(hostname -s)
prompt "Timezone [UTC]:"; read -r TZ_VAL
[ -z "$TZ_VAL" ] && TZ_VAL=UTC
echo ""

# 3. Nginx service
echo -e "${BOLD}3. Nginx Service Name${NC}"
echo "   RunCloud uses nginx-rc. Standard Linux uses nginx."
prompt "Nginx service name [auto]:"; read -r NGINX_SVC
[ -z "$NGINX_SVC" ] && NGINX_SVC=auto
echo ""

# 4. Fix server token
echo -e "${BOLD}4. Fix Server${NC}"
FIX_TOKEN=$(python3 -c "import secrets; print(secrets.token_urlsafe(32))" 2>/dev/null || head -c 32 /dev/urandom | base64 | tr -d '/+=')
info "Generated fix server token: $FIX_TOKEN"
echo ""

# 5. Monitor settings
echo -e "${BOLD}5. Monitor Thresholds (press Enter for defaults)${NC}"
prompt "Alert if RAM free below (MB) [800]:"; read -r RAM_T
[ -z "$RAM_T" ] && RAM_T=800
prompt "Alert if disk above (%) [85]:"; read -r DISK_T
[ -z "$DISK_T" ] && DISK_T=85
prompt "Ports to monitor (comma-separated, e.g. 3000,3001) [skip]:"; read -r PORTS
echo ""

# Write .env
cat > "$INSTALL_DIR/.env" << ENVEOF
# Server Monitor Bot — Generated by setup.sh
TELEGRAM_BOT_TOKEN=${BOT_TOKEN}
TELEGRAM_CHAT_ID=${CHAT_ID}
FIX_SERVER_TOKEN=${FIX_TOKEN}
FIX_SERVER_URL=http://127.0.0.1:3011
FIX_SERVER_PORT=3011
FIX_SERVER_HOST=127.0.0.1
MONITOR_SERVER_NAME=${SERVER_NAME}
MONITOR_TIMEZONE=${TZ_VAL}
NGINX_SERVICE=${NGINX_SVC}
MONITOR_RAM_THRESHOLD=${RAM_T}
MONITOR_DISK_THRESHOLD=${DISK_T}
MONITOR_PORTS=${PORTS}
MONITOR_COOLDOWN=1800
ENVEOF
info ".env written to $INSTALL_DIR/.env"

# Install Python deps
echo ""
echo -e "${BOLD}Installing Python dependencies...${NC}"
python3 -m pip install requests --quiet --break-system-packages 2>/dev/null || \
python3 -m pip install requests --quiet 2>/dev/null || \
warn "Could not install 'requests' — run: pip3 install requests"
info "Dependencies ready"

# Set up monitor cron
echo ""
echo -e "${BOLD}Setting up monitor cron (every 10 minutes)...${NC}"
chmod +x "$INSTALL_DIR/monitor.sh"
CRON_LINE="*/10 * * * * $INSTALL_DIR/monitor.sh >> /tmp/server-monitor.log 2>&1"
( crontab -l 2>/dev/null | grep -v 'monitor.sh' ; echo "$CRON_LINE" ) | crontab -
info "Cron set: $CRON_LINE"

# Set up bot as systemd service
echo ""
echo -e "${BOLD}Setting up Telegram bot as systemd service...${NC}"
SERVICE_FILE="/etc/systemd/system/server-monitor-bot.service"
sudo tee "$SERVICE_FILE" > /dev/null << SVCEOF
[Unit]
Description=Server Monitor Telegram Bot
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/python3 ${INSTALL_DIR}/bot.py
Restart=always
RestartSec=5
EnvironmentFile=${INSTALL_DIR}/.env

[Install]
WantedBy=multi-user.target
SVCEOF

# Set up fix-server as systemd service
sudo tee /etc/systemd/system/server-fix-server.service > /dev/null << SVCEOF
[Unit]
Description=Server Fix API
After=network.target

[Service]
Type=simple
WorkingDirectory=${INSTALL_DIR}
ExecStart=/usr/bin/python3 ${INSTALL_DIR}/fix-server.py
Restart=always
RestartSec=5
EnvironmentFile=${INSTALL_DIR}/.env

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable --now server-monitor-bot server-fix-server 2>/dev/null
info "Services started: server-monitor-bot + server-fix-server"

# Test alert
echo ""
echo -e "${BOLD}Sending test alert to Telegram...${NC}"
TEST_MSG="✅ Server Monitor Bot is live on *${SERVER_NAME}*\n\nMonitoring: RAM, Disk, Load, ${NGINX_SVC}\nFix API: ready\n\nSend /help to your bot to see all commands."
curl -sf -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
    -H "Content-Type: application/json" \
    -d "{\"chat_id\":\"${CHAT_ID}\",\"text\":\"${TEST_MSG}\",\"parse_mode\":\"Markdown\"}" > /dev/null 2>&1 && \
    info "Test alert sent!" || warn "Could not send test alert — check bot token and chat ID"

echo ""
echo -e "${BOLD}═══════════════════════════════════════${NC}"
echo -e "${BOLD}   Setup Complete!${NC}"
echo -e "${BOLD}═══════════════════════════════════════${NC}"
echo ""
echo "  Bot:       systemctl status server-monitor-bot"
echo "  Fix API:   systemctl status server-fix-server"
echo "  Logs:      journalctl -fu server-monitor-bot"
echo "  Test:      send /status to your Telegram bot"
echo ""
